version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper_test
    ports:
      - '2181:2181'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka_test
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
      - zookeeper
  postgres:
    image: postgres:alpine
    container_name: postgres_test
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
